"""
SQLAlchemy ORM models for the Roommate Chore Manager.
Defines all database tables using declarative base.
"""
from __future__ import annotations

import enum
from datetime import datetime

from sqlalchemy import (
    Boolean, Column, DateTime, Enum, ForeignKey,
    Integer, String, Text, JSON
)
from sqlalchemy.orm import DeclarativeBase, relationship


class Base(DeclarativeBase):
    """Base class for all ORM models."""
    pass


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class FrequencyType(str, enum.Enum):
    DAILY = "daily"
    WEEKLY = "weekly"
    MONTHLY = "monthly"
    EVERY_N_DAYS = "every_n_days"
    SPECIFIC_WEEKDAYS = "specific_weekdays"


class AssignmentStatus(str, enum.Enum):
    PENDING = "pending"
    COMPLETED = "completed"
    MISSED = "missed"
    HANDED_OVER = "handed_over"
    SWAPPED = "swapped"


class HandoverStatus(str, enum.Enum):
    REQUESTED = "requested"
    ACCEPTED = "accepted"
    CANCELLED = "cancelled"


class SwapStatus(str, enum.Enum):
    REQUESTED = "requested"
    ACCEPTED = "accepted"
    REJECTED = "rejected"


# ---------------------------------------------------------------------------
# Models
# ---------------------------------------------------------------------------

class User(Base):
    """Represents a flat member."""
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, autoincrement=True)
    telegram_id = Column(Integer, unique=True, nullable=False, index=True)
    username = Column(String(64), nullable=True)
    name = Column(String(128), nullable=False)
    active = Column(Boolean, default=True, nullable=False)
    is_admin = Column(Boolean, default=False, nullable=False)
    vacation_start = Column(DateTime, nullable=True)
    vacation_end = Column(DateTime, nullable=True)
    joined_date = Column(DateTime, default=datetime.utcnow, nullable=False)

    # Relationships
    assignments = relationship("Assignment", back_populates="user", foreign_keys="Assignment.user_id")
    handovers_given = relationship("Handover", back_populates="from_user", foreign_keys="Handover.from_user_id")
    handovers_taken = relationship("Handover", back_populates="to_user", foreign_keys="Handover.to_user_id")
    swap_requests = relationship("Swap", back_populates="requester", foreign_keys="Swap.requester_id")
    statistics = relationship("Statistics", back_populates="user", uselist=False)

    def is_on_vacation(self, date: datetime) -> bool:
        """Check if the member is on vacation on a given date."""
        if self.vacation_start and self.vacation_end:
            return self.vacation_start <= date <= self.vacation_end
        return False

    def __repr__(self) -> str:
        return f"<User id={self.id} name={self.name!r}>"


class Chore(Base):
    """Represents a household chore with its scheduling config."""
    __tablename__ = "chores"

    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String(128), nullable=False)
    description = Column(Text, nullable=True)
    enabled = Column(Boolean, default=True, nullable=False)
    reminder_message = Column(Text, nullable=True)
    group_name = Column(String(64), nullable=True)  # e.g. "Kitchen", "Bathroom"

    # Frequency config
    frequency = Column(Enum(FrequencyType), nullable=False)
    # For WEEKLY: store weekday name e.g. "Sunday"
    # For SPECIFIC_WEEKDAYS: JSON list e.g. ["Monday","Wednesday","Friday"]
    # For EVERY_N_DAYS: store the integer N
    # For MONTHLY: store day-of-month integer
    frequency_config = Column(JSON, nullable=True)

    # Reminder times stored as JSON list of "HH:MM" strings
    # e.g. ["09:00", "20:30"]
    reminder_times = Column(JSON, nullable=False, default=list)

    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    # Relationships
    assignments = relationship("Assignment", back_populates="chore", cascade="all, delete-orphan")

    def __repr__(self) -> str:
        return f"<Chore id={self.id} name={self.name!r} freq={self.frequency}>"


class Assignment(Base):
    """
    A single scheduled assignment: who does what chore on which date.
    Generated by the AssignmentEngine for the next 30 days.
    """
    __tablename__ = "assignments"

    id = Column(Integer, primary_key=True, autoincrement=True)
    chore_id = Column(Integer, ForeignKey("chores.id"), nullable=False)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    scheduled_date = Column(DateTime, nullable=False)
    status = Column(Enum(AssignmentStatus), default=AssignmentStatus.PENDING, nullable=False)
    completed_at = Column(DateTime, nullable=True)
    # Which reminder index (0, 1, 2…) this belongs to for multi-reminder chores
    reminder_index = Column(Integer, default=0, nullable=False)
    # Track if reminder was sent
    reminder_sent = Column(Boolean, default=False, nullable=False)
    overdue_notified = Column(Boolean, default=False, nullable=False)

    # Relationships
    chore = relationship("Chore", back_populates="assignments")
    user = relationship("User", back_populates="assignments", foreign_keys=[user_id])
    handover = relationship("Handover", back_populates="assignment", uselist=False)
    swaps = relationship("Swap", back_populates="assignment", foreign_keys="Swap.assignment_id")

    def __repr__(self) -> str:
        return f"<Assignment id={self.id} chore={self.chore_id} user={self.user_id} date={self.scheduled_date.date()}>"


class Handover(Base):
    """
    A handover request — one member asks others to take over their assignment.
    """
    __tablename__ = "handovers"

    id = Column(Integer, primary_key=True, autoincrement=True)
    assignment_id = Column(Integer, ForeignKey("assignments.id"), nullable=False)
    from_user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    to_user_id = Column(Integer, ForeignKey("users.id"), nullable=True)  # set when accepted
    reason = Column(Text, nullable=True)
    status = Column(Enum(HandoverStatus), default=HandoverStatus.REQUESTED, nullable=False)
    requested_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    accepted_at = Column(DateTime, nullable=True)

    # Relationships
    assignment = relationship("Assignment", back_populates="handover")
    from_user = relationship("User", back_populates="handovers_given", foreign_keys=[from_user_id])
    to_user = relationship("User", back_populates="handovers_taken", foreign_keys=[to_user_id])

    def __repr__(self) -> str:
        return f"<Handover id={self.id} status={self.status}>"


class Swap(Base):
    """
    A swap request between two members for future assignments.
    """
    __tablename__ = "swaps"

    id = Column(Integer, primary_key=True, autoincrement=True)
    assignment_id = Column(Integer, ForeignKey("assignments.id"), nullable=False)
    requester_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    target_user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    # The assignment the requester wants to swap their chore with
    target_assignment_id = Column(Integer, ForeignKey("assignments.id"), nullable=True)
    status = Column(Enum(SwapStatus), default=SwapStatus.REQUESTED, nullable=False)
    requested_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    responded_at = Column(DateTime, nullable=True)

    # Relationships
    assignment = relationship("Assignment", back_populates="swaps", foreign_keys=[assignment_id])
    requester = relationship("User", back_populates="swap_requests", foreign_keys=[requester_id])

    def __repr__(self) -> str:
        return f"<Swap id={self.id} status={self.status}>"


class Statistics(Base):
    """Aggregated per-user statistics."""
    __tablename__ = "statistics"

    id = Column(Integer, primary_key=True, autoincrement=True)
    user_id = Column(Integer, ForeignKey("users.id"), unique=True, nullable=False)
    total_completed = Column(Integer, default=0, nullable=False)
    total_missed = Column(Integer, default=0, nullable=False)
    handovers_given = Column(Integer, default=0, nullable=False)
    handovers_taken = Column(Integer, default=0, nullable=False)
    current_streak = Column(Integer, default=0, nullable=False)
    longest_streak = Column(Integer, default=0, nullable=False)

    # Relationships
    user = relationship("User", back_populates="statistics")

    @property
    def completion_percentage(self) -> float:
        total = self.total_completed + self.total_missed
        if total == 0:
            return 0.0
        return round((self.total_completed / total) * 100, 1)

    def __repr__(self) -> str:
        return f"<Statistics user={self.user_id} completed={self.total_completed}>"


class Settings(Base):
    """Bot-wide settings stored per key-value in DB."""
    __tablename__ = "settings"

    id = Column(Integer, primary_key=True, autoincrement=True)
    key = Column(String(64), unique=True, nullable=False)
    value = Column(Text, nullable=True)

    def __repr__(self) -> str:
        return f"<Settings key={self.key!r}>"
